### ISSUE TITLE
About nnet.utils.vis_utils

### ISSUE THREAD

**Issue by iseefirehy** [dnlcrl/deep-residual-networks-pyfunt#3]
Hi, I tried to run code but I have an error with the nnet.utils.vis_utils. I think that is not a package in python. Is that a user-defined module? How can get the access to use it?

Thanks

**Comment by dnlcrl** [comment]
Hi, maybe you are referring to this file https://github.com/dnlcrl/PyFunt/blob/master/pyfunt/utils/vis_utils.py

**Comment by iseefirehy** [comment]
Thanks! That's what I want.
